# Generated by Django 5.1 on 2024-08-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_main', '0002_authors_remove_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Library_main.authors'),
            preserve_default=False,
        ),
    ]
