# Generated by Django 5.1 on 2024-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_main', '0003_books_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='filename',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
