# Generated by Django 5.1 on 2024-08-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_main', '0004_books_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=1000)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_main.books')),
            ],
        ),
    ]
